server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.2.0"
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
    
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      local: true
      soundcloud: true # Opcional: Recomendado tenerlo de respaldo
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5

metrics:
  prometheus:
    enabled: false

logging:
  level:
    root: INFO
    lavalink: INFO

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    
  # Configuración de tu plugin LavaSrc
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    spotify:
      clientId: "TU_SPOTIFY_CLIENT_ID"  
      clientSecret: "TU_SPOTIFY_CLIENT_SECRET"  
      countryCode: "MX" 
      playlistLoadLimit: 6 
      albumLoadLimit: 6